---
interfaces:
    - !interface
        name: colormap
        friendly_name: Lights
        template: bulb.html

installed_drivers:
    - !driver
        name: bulb
        module: bulb
        klass: Bulb
        interface: colormap
    - !driver
        name: motion
        module: motion
        klass: MotionController

devices:
    living_room:
        - !device
            name: Left
            driver: bulb
            config:
            - host: 172.16.42.201
        - !device
            name: Right
            driver: bulb
            config:
            - host: 172.16.42.203

    bedroom:
        - !device
            name: Bed
            driver: bulb
            config:
            - host: 192.168.1.123
        - !device
            name: cam1
            driver: motion
            key: cam1
            config:
            - thread: 1

actions:
    - !action
      name: arm
      devices:
      - name: cam1
        method: start_detection
    - !action
      name: disable
      devices:
      - name: cam1
        method: stop_detection

config:
    - location