---
interfaces:
    - !interface
        name: colormap
        friendly_name: Lights
        template: bulb.html

installed_drivers:
    - !driver
        name: bulb
        module: bulb
        klass: Bulb
        interface: colormap
    - !driver
        name: motion
        module: motion
        klass: MotionController

devices:
    living_room:
        - !device
            name: Left
            driver: bulb
            config:
            - host: 192.168.1.124
        - !device
            name: Right
            driver: bulb
            config:
            - host: 192.168.1.125

    bedroom:
        - !device
            name: Bed
            driver: bulb
            config:
            - host: 192.168.1.123
        - !device
            name: cam1
            driver: motion
            key: cam1
            config:
            - thread: 1
        - !device
            name: sleep
            key: sleep

actions:
    - !action
      name: arm
      devices:
      - name: cam1
        method: start_detection
    - !action
      name: disable
      devices:
      - name: cam1
        method: stop_detection
    - !action
      name: alert
      devices:
      - name: Bed
        method: change_color
        config:
         white: 255
    - !action
      name: sleep
      devices:
      - name: Bed
        method: change_color
        config:
         white: 0
    - !action
      name: wake
      devices:
      - name: Bed
        method: change_color
        config:
         white: 255
    - !action
      name: living room on
      devices:
      - name: Left
        method: change_color
        config:
         white: 255
      - name: Right
        method: change_color
        config:
         white: 255
    - !action
      name: movie mode
      devices:
      - name: Left
        method: change_color
        config:
         red: 16
         blue: 30
      - name: Right
        method: change_color
        config:
         red: 16
         blue: 30


config:
    - location: Des Moines