---
installed_drivers:
    - !driver
        typeof: device
        name: bulb
        module: bulb
        klass: Bulb
    - !driver
        typeof: sensor
        name: motion
        module: motion
        klass: MotionController

devices:
    living_room:
        - !device
            name: Left
            driver: bulb
            config:
            - host: 172.16.42.201
        - !device
            name: Right
            driver: bulb
            config:
            - host: 172.16.42.203

    bedroom:
        - !device
            name: Bed
            driver: bulb
            config:
            - host: 192.168.1.123
        - !sensor
            name: cam1
            driver: motion
            key: cam1
