---
interfaces:
    - !interface
        name: colormap
        friendly_name: Lights
        template: bulb.html
    - !interface
        name: music
        friendly_name: Music
        template: music.html

installed_drivers:
    - !driver
        name: bulb
        module: bulb
        klass: Bulb
        interface: colormap
    - !driver
        name: motion
        module: motion
        klass: MotionController
    - !driver
        name: plug
        module: plug
        klass: Plug
    - !driver
        name: wol
        module: wol
        klass: WakeOnLAN
    - !driver
        name: sshfirewall
        module: firewall
        klass: SSHFirewall
    - !driver
        name: mopidy
        module: mopidy
        klass: Mopidy
        interface: music

devices:
    living_room:
        - !device
            name: Left
            driver: bulb
            config:
             host: 192.168.1.124
        - !device
            name: Right
            driver: bulb
            config:
             host: 192.168.1.125
        - !device
            name: Cabinet
            driver: plug
            config:
             host: 192.168.1.126
             mac: B4:43:0D:C1:CB:18
        - !device
            name: r1
            driver: sshfirewall
            config:
             host: 172.24.0.1
             keyfile: /srv/www/home/.ssh/id_rsa
             path: /usr/sbin/iptables
        - !device
            name: media
            driver: mopidy
            config:
             host: localhost

    bedroom:
        - !device
            name: Bed
            driver: bulb
            config:
             host: 192.168.1.123
        - !device
            name: cam1
            driver: motion
            key: cam1
            config:
             thread: 1
        - !device
            name: Desktop
            driver: wol
            config:
             mac: 44:8a:5b:2c:38:d9
             manual_interface: eno1

actions:
    - !action
      name: arm
      devices:
      - name: cam1
        method: start_detection
    - !action
      name: disable
      devices:
      - name: cam1
        method: stop_detection
    - !action
      name: alert
      devices:
      - name: Bed
        method: change_color
        config:
         white: 255
    - !action
      name: sleep
      devices:
      - name: Bed
        method: change_color
        config:
         white: 0
    - !action
      name: wake
      devices:
      - name: Bed
        method: fade_sunlight
      - name: Desktop
        method: wake
    - !action
      name: living room on
      devices:
      - name: Left
        method: sunlight
      - name: Right
        method: sunlight
    - !action
      name: living room off
      devices:
      - name: Left
        method: change_color
        config:
         white: 0
      - name: Right
        method: change_color
        config:
         white: 0
      - name: Cabinet
        method: 'off'
    - !action
      name: movie mode
      devices:
      - name: Left
        method: change_color
        config:
         white: 10
         mode: '41'
      - name: Right
        method: change_color
        config:
         white: 10
         mode: '41'
      - name: Cabinet
        method: 'off'
    - !action
      name: party mode
      devices:
      - name: Left
        method: change_color
        config:
         mode: '61'
         function: '25'
         speed: '0a'
      - name: Right
        method: change_color
        config:
         mode: '61'
         function: '25'
         speed: '0a'
      - name: Cabinet
        method: 'on'
    - !action
      name: bedroom occupied
      devices:
      - name: Bed
        method: sunlight
    - !action
      name: bedroom vacant
      devices:
      - name: cam1
        method: stop_detection
      - name: Bed
        method: change_color
        config:
         white: 0
      - name: cam1
        delay: 1
        method: start_detection
    - !action
      name: unblock
      devices:
      - name: r1
        method: unblock
